# Breakdown of Validation

## Xeon Regression

## Xeon Coherency

## Chiplset Chassis SOC Validation

## Chiplet Chassis IP Validation

## Platform Validation

# Validation Domains

## NOC/Coherency

## CXL/CXi

## Memory

## Core

## Ethernet

## PM

## Security

## RAS

# Post-Si Validation Disciplines

## Functional Validation (FV)

## Electrical Validation (EV)

## Power and Performance (PnP)

## Platform Validation (PlatVal)

## Circuit Marginality Validation (CMV)

## Processor Platform Validation (PPV)
