# Glossary

Table: Glossary of Terms


|**Term**  |  **Definition** |
|-------|--------------------|  
|**Sample**|   Sample|
----------  ------------------------------------------------------------------------------