---
title: Validation Platform Strategy
date: 2022/02/02
author: Brad Friemdan
...

**Intel Confidential**

[!_LegalNotice.mmd]

# Revision History

Table:  Revision History

|**Version**|   **Description** |   **Author**      |  **Date**     |
|-------    |   -----------     |   ------          |  --------     |
|0.0        | Initial Outline   |   Brad Friedman   |   02/04/22    |


# References

Table:  Reference List

Title           Description
-------         -----------
<sample>        <sample>

# Contacts

Table:  Contact List

Name 	        Role
---- 	        ----
Brad Friedman  	VSE Lead Validation Architect

# Introduction 

## Purpose of Document

## Post-Si Validation TR Process

<put stuff here>

[!_Glossary.mmd]

# Open Items

This section provides a list of architectural items with discussions that are currently in progress so are not yet resolved in this HAS release.


## TODOs

```opens("TODO", numbered=True)
```

## FIXMEs

```opens("FIXME", numbered=True)
```